// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-listings.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { z } from "npm:zod@^3.25.76";
var search_listings_default = defineTool({
  name: "search_listings",
  title: "Search listings",
  description: "Search active public real-estate listings on Elan24 by keyword, category slug, region, deal type (satilir/kiraye), and price range.",
  inputSchema: {
    query: z.string().optional().describe("Free-text search on title/description."),
    category_slug: z.string().optional().describe("Category slug, e.g. 'menziller'."),
    region: z.string().optional().describe("Region/city name."),
    deal_type: z.enum(["satilir", "kiraye"]).optional().describe("Sale or rent."),
    min_price: z.number().optional(),
    max_price: z.number().optional(),
    limit: z.number().optional().describe("Max results (default 20, cap 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false } }
    );
    const limit = Math.min(input.limit ?? 20, 50);
    let q = supabase.from("listings").select("id,title,price,currency,region,category_slug,deal_type,created_at,image_urls").eq("status", "active").order("created_at", { ascending: false }).limit(limit);
    if (input.query) q = q.ilike("title", `%${input.query}%`);
    if (input.category_slug) q = q.eq("category_slug", input.category_slug);
    if (input.region) q = q.ilike("region", `%${input.region}%`);
    if (input.deal_type) q = q.eq("deal_type", input.deal_type);
    if (input.min_price != null) q = q.gte("price", input.min_price);
    if (input.max_price != null) q = q.lte("price", input.max_price);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { listings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-listings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_my_listings_default = defineTool2({
  name: "get_my_listings",
  title: "Get my listings",
  description: "Return listings owned by the currently signed-in Elan24 user.",
  inputSchema: {
    status: z2.enum(["active", "pending", "rejected", "sold", "expired"]).optional(),
    limit: z2.number().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const limit = Math.min(input.limit ?? 20, 100);
    let q = supabase.from("listings").select("id,title,price,currency,status,category_slug,deal_type,views_count,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (input.status) q = q.eq("status", input.status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { listings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in Elan24 user's profile (name, phone, balance, avatar).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qkeymzkgymmceclilaot";
var mcp_default = defineMcp({
  name: "elan24-mcp",
  title: "Elan24",
  version: "0.1.0",
  instructions: "Elan24 is an Azerbaijani real-estate classifieds platform. Use search_listings for public property search, and get_my_listings / get_my_profile for the signed-in user's own data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_listings_default, get_my_listings_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
