INSERT INTO public.translations (key, az, ru, category) VALUES
('common.all', 'Hamısı', 'Все', 'common'),
('common.loading', 'Yüklənir...', 'Загрузка...', 'common'),
('common.cancel', 'Ləğv et', 'Отмена', 'common'),
('common.delete', 'Sil', 'Удалить', 'common'),
('common.error', 'Xəta', 'Ошибка', 'common'),
('common.user', 'İstifadəçi', 'Пользователь', 'common'),
('common.unnamed', 'Adsız', 'Без имени', 'common'),
('time.just_now', 'Az əvvəl', 'Только что', 'common'),
('time.hours_ago', '{{count}} saat əvvəl', '{{count}} ч. назад', 'common'),
('time.days_ago', '{{count}} gün əvvəl', '{{count}} дн. назад', 'common'),
('products.search_placeholder', 'Məhsul axtar...', 'Поиск товара...', 'products'),
('products.filters', 'Filterlər', 'Фильтры', 'products'),
('products.condition', 'Vəziyyət', 'Состояние', 'products'),
('products.condition_new', 'Yeni', 'Новый', 'products'),
('products.condition_like_new', 'Yeni kimi', 'Как новый', 'products'),
('products.condition_used', 'İşlənmiş', 'Б/у', 'products'),
('products.region', 'Bölgə', 'Регион', 'products'),
('products.select_region', 'Bölgə seçin', 'Выберите регион', 'products'),
('products.price_range', 'Qiymət aralığı (₼)', 'Диапазон цен (₼)', 'products'),
('products.min', 'Min', 'Мин', 'products'),
('products.max', 'Max', 'Макс', 'products'),
('products.category_filters', 'Kateqoriyaya özəl filtrlər', 'Фильтры категории', 'products'),
('products.select', 'Seçin', 'Выберите', 'products'),
('products.clear_filters', 'Filterləri sıfırla', 'Сбросить фильтры', 'products'),
('products.results_count', '{{count}} elan tapıldı', 'Найдено объявлений: {{count}}', 'products'),
('products.no_results_title', 'Elan tapılmadı', 'Объявления не найдены', 'products'),
('products.no_results_desc', 'Axtarış meyarlarınızı dəyişməyi yoxlayın', 'Попробуйте изменить параметры поиска', 'products'),
('products.sort_newest', 'Ən yeni', 'Самые новые', 'products'),
('products.sort_price_asc', 'Ucuzdan bahaya', 'Сначала дешевые', 'products'),
('products.sort_price_desc', 'Bahadan ucuza', 'Сначала дорогие', 'products'),
('products.sort_views', 'Ən çox baxılan', 'Самые просматриваемые', 'products'),
('detail.back', 'Geri qayıt', 'Назад', 'product_detail'),
('detail.back_to_listings', 'Elanlara qayıt', 'Вернуться к объявлениям', 'product_detail'),
('detail.listing_not_found', 'Elan tapılmadı', 'Объявление не найдено', 'product_detail'),
('detail.delivery_available', 'Çatdırılma var', 'Есть доставка', 'product_detail'),
('detail.delivery_unavailable', 'Çatdırılma yoxdur', 'Нет доставки', 'product_detail'),
('detail.views', '{{count}} baxış', '{{count}} просмотров', 'product_detail'),
('detail.watch_reels', 'Reels-də izlə', 'Смотреть в Reels', 'product_detail'),
('detail.in_favorites', 'Seçilmişlərdə', 'В избранном', 'product_detail'),
('detail.add_favorite', 'Seçilmişlərə əlavə et', 'Добавить в избранное', 'product_detail'),
('detail.remove_favorite_success', 'Seçilmişlərdən silindi', 'Удалено из избранного', 'product_detail'),
('detail.add_favorite_success', 'Seçilmişlərə əlavə edildi', 'Добавлено в избранное', 'product_detail'),
('detail.delete_listing_title', 'Elanı silmək istəyirsiniz?', 'Удалить объявление?', 'product_detail'),
('detail.delete_irreversible', 'Bu əməliyyat geri alına bilməz.', 'Это действие нельзя отменить.', 'product_detail'),
('detail.listing_deleted', 'Elan silindi', 'Объявление удалено', 'product_detail'),
('detail.description', 'Təsvir', 'Описание', 'product_detail'),
('detail.product_info', 'Məhsul məlumatları', 'Информация о товаре', 'product_detail'),
('detail.category', 'Kateqoriya', 'Категория', 'product_detail'),
('detail.city', 'Şəhər', 'Город', 'product_detail'),
('detail.currency', 'Valyuta', 'Валюта', 'product_detail'),
('detail.views_count', 'Baxış sayı', 'Количество просмотров', 'product_detail'),
('detail.created_date', 'Yerləşdirmə tarixi', 'Дата размещения', 'product_detail'),
('detail.sale', 'Satış', 'Продажа', 'product_detail'),
('detail.direct_purchase_available', 'Birbaşa alış mümkündür', 'Доступна прямая покупка', 'product_detail'),
('detail.shipping_methods', 'Çatdırılma üsulları', 'Способы доставки', 'product_detail'),
('detail.delivery', 'Çatdırılma', 'Доставка', 'product_detail'),
('detail.free', 'Pulsuz', 'Бесплатно', 'product_detail'),
('detail.review_count', '{{count}} rəy', '{{count}} отзывов', 'product_detail'),
('detail.buy_now', 'İndi al', 'Купить сейчас', 'product_detail'),
('detail.contact_store', 'Mağaza ilə əlaqə', 'Связаться с магазином', 'product_detail'),
('detail.no_number', 'Nömrə yoxdur', 'Номер отсутствует', 'product_detail'),
('detail.show_number', 'Nömrəni göstər', 'Показать номер', 'product_detail'),
('detail.send_message', 'Mesaj yaz', 'Написать сообщение', 'product_detail'),
('detail.following', 'İzləyirsən', 'Вы подписаны', 'product_detail'),
('detail.follow', 'İzlə', 'Подписаться', 'product_detail'),
('detail.follow_stopped', 'İzləmə dayandırıldı', 'Подписка отменена', 'product_detail'),
('detail.comments', 'Şərhlər ({{count}})', 'Комментарии ({{count}})', 'product_detail'),
('detail.replying_to', '{{name}} istifadəçisinə cavab yazırsınız...', 'Вы отвечаете пользователю {{name}}...', 'product_detail'),
('detail.reply_placeholder', 'Cavabınız...', 'Ваш ответ...', 'product_detail'),
('detail.comment_placeholder', 'Şərhiniz...', 'Ваш комментарий...', 'product_detail'),
('detail.send', 'Göndər', 'Отправить', 'product_detail'),
('detail.login_to_comment', 'Şərh yazmaq üçün daxil olun', 'Войдите, чтобы написать комментарий', 'product_detail'),
('detail.reply', 'Cavab yaz', 'Ответить', 'product_detail'),
('detail.delete_comment_title', 'Şərhi silmək istəyirsiniz?', 'Удалить комментарий?', 'product_detail'),
('detail.no_comments', 'Hələ şərh yoxdur. İlk şərhi siz yazın!', 'Комментариев пока нет. Будьте первым!', 'product_detail'),
('detail.similar_listings', 'Oxşar elanlar', 'Похожие объявления', 'product_detail'),
('detail.share', 'Paylaş', 'Поделиться', 'product_detail'),
('detail.share_desc', 'Bu elanı dostlarınızla paylaşın', 'Поделитесь этим объявлением с друзьями', 'product_detail'),
('detail.qr_scan_copy', 'QR kodu skan et və ya kopyala', 'Сканируйте QR-код или скопируйте ссылку', 'product_detail'),
('detail.copy', 'Kopyala', 'Копировать', 'product_detail'),
('detail.link_copied', 'Link kopyalandı!', 'Ссылка скопирована!', 'product_detail'),
('level.vip_seller', 'VIP Satıcı', 'VIP продавец', 'levels'),
('level.trusted', 'Etibarlı', 'Надежный', 'levels'),
('level.active', 'Aktiv', 'Активный', 'levels'),
('level.new', 'Yeni', 'Новый', 'levels')
ON CONFLICT (key) DO NOTHING;